//公共的配置信息
module.exports={
    email:{
        server:'QQ',
        user:'3320407219@qq.com',
        pass:'qbjatflpssyrchje'
    },
    mysql:{
        host:'192.168.97.247',
        user:'root',
        password:'root',
        database:'merchandise'
    }
}